<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>9.0</LangVersion>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <ProjectReference Include="../SAM.Batch/SAM.Batch.csproj" />
    <ProjectReference Include="../SAM.Game/SAM.Game.csproj" />
    <ProjectReference Include="../SAM.Picker/SAM.Picker.csproj" />
  </ItemGroup>
</Project>
