<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.0.0</Version>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <Authors>wyfang</Authors>
    <Description>Steam Stats Editor asynchronous submission coordinator.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SAM.Batch/SAM.Batch.csproj" />
  </ItemGroup>
</Project>
