<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>Steam Stats Editor</AssemblyTitle>
    <Company>Gibbed</Company>
    <Authors>Gibbed; wyfang</Authors>
    <Description>Steam statistics text import, export and staged submission, derived from Steam Achievement Manager.</Description>
    <Copyright>Copyright © Gibbed 2019</Copyright>
  </PropertyGroup>
  <PropertyGroup>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Blank.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
    <RepositoryUrl>https://github.com/wyfang/steam-stats-editor</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
    <OutputPath>..\bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <OutputPath>..\upload\</OutputPath>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="DoubleBufferedListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Manager.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAM.API\SAM.API.csproj" />
    <ProjectReference Include="..\SAM.Batch\SAM.Batch.csproj" />
    <ProjectReference Include="..\SAM.Submission\SAM.Submission.csproj" />
  </ItemGroup>
</Project>
